### ISSUE TITLE
SSL with loadbalancer

### ISSUE THREAD

**Issue by apertureless** [cptactionhank/docker-atlassian-jira-software#13]
Hi, I'm running this container in rancher. 
I setup a loadbalancer with ssl and changed the baseurl in the jira configs to http://jira.mydomain.com 

However I still get an `Mismatched URL` Scheme error and images and widgets are not loaded properly, becuase it still has the http instead of https in it.

**Comment by cptactionhank** [comment]
Please elaborate on your networking setup and where SSL and or load balancing is done and how you create the container as well.

Kind regards,

Martin Jensen

**Comment by apertureless** [comment]
I am managing the containers with rancher.

Heres my docker compose for jira: 

``` yml
jira-software-container:
  ports:
  - 10088:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: cptactionhank/atlassian-jira-software:latest
  links:
  - postgress:postgress-db
  volumes:
  - /srv/docker/atlassian/jira:/var/atlassian/jira
  stdin_open: true
postgress:
  ports:
  - 5432:5432/tcp
  environment:
    POSTGRES_USER: ****
    POSTGRES_PASSWORD: *****
    POSTGRES_DB: jira
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: postgres:latest
  volumes:
  - /srv/docker/postgresql:/var/lib/postgresql
  stdin_open: true
```

The lb is listening on 443 (ssl termination) and is forwarding to the service.

However, jira per se is working. But some gadgets are not. And some icons are not.

Error log:

```
2016-08-08 11:17:45,844 http-apr-8080-exec-22 ERROR anonymous 677x1527x1 1b3yinw 94.79.175.190,10.42.108.165 /plugins/servlet/gadgets/dashboard-diagnostics [c.a.g.d.internal.diagnostics.DiagnosticsServlet] DIAGNOSTICS: FAILED
com.atlassian.gadgets.dashboard.internal.diagnostics.UrlSchemeMismatchException: Detected URL scheme, 'http', does not match expected scheme 'https'
    at com.atlassian.gadgets.dashboard.internal.diagnostics.Diagnostics.checkExpectedScheme(Diagnostics.java:52)
```

I guess its a problem with the default jira conifg https://confluence.atlassian.com/jirakb/login-gadget-and-dashboard-don-t-work-when-running-behind-a-load-balancer-256868360.html

I found some resolutions on the atlassian forums, however I would have to change the server.xml for that. 

Would be great if you could include the scheme, proxyName and proxyPort as enviroment variables or something like this.
