### ISSUE TITLE
JIRA Startup Failed

### ISSUE THREAD

**Issue by elderone** [cptactionhank/docker-atlassian-jira-software#6]
JIRA Startup Failed
The following plugins are required by JIRA, but have not been started:
Gadget Directory Plugin (com.atlassian.gadgets.directory)
Atlassian JIRA - Plugins - Gadgets Plugin (com.atlassian.jira.gadgets)
Atlassian JIRA - Plugins - Global Issue Navigator (com.atlassian.jira.jira-issue-nav-plugin)
Atlassian JIRA - Plugins - Quick Edit Plugin (com.atlassian.jira.jira-quick-edit-plugin)
Atlassian JIRA - Plugins - REST Plugin (com.atlassian.jira.rest)

first start, begin of evaluation install

docker-compose.yml:

```
data:
  image: busybox
  volumes:
    - /home/data/jira/home:/var/atlassian/jira
    - /home/data/jira/logs:/opt/atlassian/jira/logs

server:
  image: cptactionhank/atlassian-jira-software:latest
  volumes_from:
    - data
  ports:
    - 127.0.0.1:8080:8080
```

permissions are right:
`sudo chown daemon:docker -R /home/data/jira`

**Comment by elderone** [comment]
[solution](https://answers.atlassian.com/questions/285853/answers/3342617)
need to add -Datlassian.plugins.enable.wait=300 argument

**Comment by elderone** [comment]
resolve it:
docker-compose.yml:

```
data:
  image: busybox
  volumes:
    - /home/data/jira/home:/var/atlassian/jira
    - /home/data/jira/logs:/opt/atlassian/jira/logs

server:
  image: cptactionhank/atlassian-jira-software:latest
  volumes_from:
    - data
  ports:
    - 127.0.0.1:8080:8080
  environment:
    - CATALINA_OPTS=-Datlassian.plugins.enable.wait=300
```
