### ISSUE TITLE
Can't mount local installation directory

### ISSUE THREAD

**Issue by 3579km** [cptactionhank/docker-atlassian-jira-software#65]
Need to edit dbconfig.xml file, due to this I'm mounting jira installation directory along with jira home dir. But container not starting after adding second volume (D:/Work/Docker-drives/jira-software/opt/atlassian/jira:/opt/atlassian/jira).

My docker-compose config (docker on Windows):

```
version: "3"

services:
  jira:
    container_name: jira
    restart: unless-stopped
    image: cptactionhank/atlassian-jira-software:latest
    volumes:
      - D:/Work/Docker-drives/jira-software/var/atlassian/jira:/var/atlassian/jira
      - D:/Work/Docker-drives/jira-software/opt/atlassian/jira:/opt/atlassian/jira
      
    ports:
      - 8181:8080
```
