### ISSUE TITLE
unable to persist /opt/atlassian 

### ISSUE THREAD

**Issue by philippkayser94** [cptactionhank/docker-atlassian-jira-software#72]
Hi guys,

I'm trying to persist /opt/atlassian in order to access easier the crowd.properties and seraph-config.xml so I will store all volumes in /opt/docker/container.... permissions are checked within the container but I think it's still caused by the permissions.

Following my used docker-compose.yml . If i persist /var/atlassian only, it works fine.

```
version: '2'

services:
  db:
    container_name: jira-servicedesk_prod_db
    image: postgres
    networks:
      - servicedesk
    volumes:
      - /opt/docker/04-jira-servicedesk/db:/var/lib/postgresql/data
    ports:
     - "5432"
    environment:
     - POSTGRES_USER=jiraservicedesk
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=jiraservicedeskdb
  desk:
    container_name: jira-servicedesk_prod_desk
    image: cptactionhank/atlassian-jira-service-desk:latest
    depends_on:
      - db
    networks:
      - web
      - servicedesk
    volumes:
      - /opt/docker/04-jira-servicedesk/servicedesk/HOME:/var/atlassian/jira
      - /opt/docker/04-jira-servicedesk/servicedesk/OPT:/opt/atlassian/jira
    environment:
      - CATALINA_OPTS=-Xms786m -Xmx1g
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:servicedesk.domain.de"
      - "traefik.port=8080"
    ports:
      - "8080"

networks:
  web:
     external: true
  servicedesk:
```
